/**
 * VANT Lookbook Mock Data
 * High-end streetwear editorial lookbook catalog data with full bilingual Arabic/English fields.
 * File: src/lib/mockData.ts
 */

import { Product } from '../types/catalog';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'vant-001',
    title: 'VANT Heavyweight Boxy Tee',
    title_ar: 'تيشيرت VANT بوكسي قطن ثقيل',
    description: 'Custom-milled 280 GSM combed jersey short sleeve tee. Designed with signature exaggerated drop shoulders, reinforced double-needle collar, and raw-cut hem finish. Features minimalist VANT micro-logo in signature cobalt blue at lower flank.',
    description_ar: 'تيشيرت بأكمام قصيرة وقصّة بوكسي عصرية مصنوع من قطن جيرسي مُمشط عالي الكثافة بوزن 280 GSM. يتميز بأكتاف منسدلة وياقة معززة بحياكة مزدوجة وأطراف بحواف خام مستقيمة، مع شعار VANT المصغر باللون الأزرق الكوبالت.',
    price: 65,
    category: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cobalt Blue', 'Washed Black', 'Bone White'],
    colors_ar: ['أزرق كوبالت', 'أسود مغسول', 'أبيض عاجي'],
    fit_details: 'Architectural boxy drape. Oversized silhouette through the chest with cropped length balance.',
    fit_details_ar: 'قصّة بوكسي هندسية فضفاضة (Oversized) مع أكتاف ساقطة وتوازن مثالي في الطول.',
    material: '100% Combed Compact Cotton (280 GSM), vintage enzyme-washed.',
    material_ar: '100% قطن طبيعي مُمشط ومضغوط (280 GSM)، مغسول إنزيمياً لملمس ناعم كلاسيكي.',
    is_exclusive_drop: true,
    created_at: '2026-09-30T10:00:00Z',
    media: [
      {
        id: 'media-001-a',
        product_id: 'vant-001',
        media_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 1,
      },
      {
        id: 'media-001-b',
        product_id: 'vant-001',
        media_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 2,
      },
    ],
  },
  {
    id: 'vant-002',
    title: 'VANT Archival Distressed Zip Hoodie',
    title_ar: 'هودي VANT سحاب بتأثير عتيق معتق',
    description: 'Heavyweight 480 GSM French Terry zip hoodie with bespoke hand-distressed edge grinding on ribbed cuffs and hemline. Fitted with dual-direction matte cobalt metal zippers and deep articulated hood with double-layer cotton lining.',
    description_ar: 'هودي بسحاب مصنوع من قماش فرينش تيري الثقيل بوزن 480 GSM مع لمسات تعتيق يدوية عند أطراف الأكمام والخصر. مزود بسحاب معدني ثنائي الاتجاه باللون الكوبالت وقبعة عميقة مبطنة بطبقتين من القطن.',
    price: 145,
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Washed Onyx', 'Heather Concrete'],
    colors_ar: ['أسود أونيكس مغسول', 'رمادي خرساني'],
    fit_details: 'Generous volume through torso and sleeves with snug ribbed waist band.',
    fit_details_ar: 'حجم مريح وفضفاض في الصدر والأكمام مع خصر مضلع يمنح ثباتاً أنيقاً.',
    material: '480 GSM Heavy French Terry Cotton. Garment-dyed and sun-faded finish.',
    material_ar: '480 GSM قطن فرينش تيري ثقيل فاخر، مصبوغ ومُعالج بتأثير تلاشي أشعة الشمس الطبيعي.',
    is_exclusive_drop: true,
    created_at: '2026-09-28T14:30:00Z',
    media: [
      {
        id: 'media-002-a',
        product_id: 'vant-002',
        media_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 1,
      },
      {
        id: 'media-002-b',
        product_id: 'vant-002',
        media_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 2,
      },
    ],
  },
  {
    id: 'vant-003',
    title: 'VANT Modular Cargo Pant',
    title_ar: 'بنطال VANT كارجو تقني متعدد الجيوب',
    description: 'Technical streetwear trousers equipped with eight modular utility storage pockets, magnetic flap closures, and concealed bungee cinch cords at both leg openings to switch between wide-leg and tapered cuffs.',
    description_ar: 'بنطال ستريتوير تقني مزود بثمانية جيوب عملية متعددة الاستخدامات مع أقفال مغناطيسية، وأربطة مطاطية مخفية عند الكاحل للتحكم في وسع البنطال بين القصّة المستقيمة والضيقة.',
    price: 120,
    category: 'Pants',
    sizes: ['28-30 (S)', '31-32 (M)', '33-34 (L)', '36 (XL)'],
    colors: ['Shadow Grey', 'Matte Carbon'],
    colors_ar: ['رمادي داكن', 'كربون مطفي'],
    fit_details: 'Relaxed ergonomic straight leg with pre-shaped knee pleats for maximum mobility.',
    fit_details_ar: 'قصّة مستقيمة مريحة مع طيات مفصلية عند الركبتين لمرونة وحرية حركة كاملة.',
    material: 'Reinforced 240 GSM Cotton-Nylon blend treated with water-repellent DWR coating.',
    material_ar: 'مزيج قطن ونايلون معزز بوزن 240 GSM معالج بطبقة DWR المقاومة لرذاذ الماء والأمطار.',
    is_exclusive_drop: false,
    created_at: '2026-09-25T08:15:00Z',
    media: [
      {
        id: 'media-003-a',
        product_id: 'vant-003',
        media_url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 1,
      },
      {
        id: 'media-003-b',
        product_id: 'vant-003',
        media_url: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 2,
      },
    ],
  },
  {
    id: 'vant-004',
    title: 'VANT Minimalist Shell Jacket',
    title_ar: 'جاكيت VANT شيل تقني مضاد للرياح',
    description: 'Ultralight waterproof 3-layer technical shell engineered for transition weather. Featuring AquaGuard waterproof zippers, tonal matte storm flap, hidden chest security pocket, and interior carry sling harness.',
    description_ar: 'جاكيت خارجي تقني فائق الخفة ومقاوم للماء من 3 طبقات مصمم لمواسم التقلبات الجوية. مزود بسحابات AquaGuard المقاومة للماء، وجيب صدر أمني مخفي، وحمالة كتف داخلية لسهولة الحمل.',
    price: 195,
    category: 'Outerwear',
    sizes: ['M', 'L', 'XL'],
    colors: ['Glacier Graphite', 'Midnight Navy'],
    colors_ar: ['رمادي جليدي', 'كحلي داكن'],
    fit_details: 'Standard outerwear cut tailored for effortless layering over oversized knitwear.',
    fit_details_ar: 'قصّة جاكيت خارجية مدروسة لتنسيق سلس فوق الهوديات والملابس الصوفية الفضفاضة.',
    material: '3-Layer Ripstop Membrane with 15,000mm waterproofing and 10,000g breathability.',
    material_ar: 'غشاء ريبستوب ثلاثي الطبقات مع مقاومة ماء حتى 15,000 مم وتنفس عالي للحرارة.',
    is_exclusive_drop: true,
    created_at: '2026-09-20T12:00:00Z',
    media: [
      {
        id: 'media-004-a',
        product_id: 'vant-004',
        media_url: 'https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 1,
      },
    ],
  },
  {
    id: 'vant-005',
    title: 'VANT Cyber Balaclava Knit',
    title_ar: 'قناع VANT بالاكلافا صوف حراري',
    description: 'Seamless rib-knit thermal balaclava with convertible collar drape and breathable perforated mouth ventilation zone. Finished with cobalt jacquard VANT coordinates tag.',
    description_ar: 'قناع بالاكلافا حراري محبوك بدون درزات مع ياقة قابلة للتحويل ومسامات تهوية عند الفم. مزين برقعة إحداثيات VANT المنسوجة باللون الأزرق الكوبالت.',
    price: 48,
    category: 'Coming Soon',
    sizes: ['One Size'],
    colors: ['Pitch Black', 'Electric Cobalt'],
    colors_ar: ['أسود داكن', 'أزرق كوبالت'],
    fit_details: 'Ergonomic contouring around jaw and crown. Can be worn as snood or full mask.',
    fit_details_ar: 'تصميم يلتف بانسيابية حول ملامح الوجه والفك. يمكن ارتداؤه كوشاح رقبة أو قناع كامل.',
    material: '100% Extrafine Merino Wool & Thermal Spandex blend.',
    material_ar: '100% صوف ميرينو فائق النعومة مع خيوط إيلاستين الحرارية المرنة.',
    is_exclusive_drop: true,
    created_at: '2026-09-18T16:00:00Z',
    media: [
      {
        id: 'media-005-a',
        product_id: 'vant-005',
        media_url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1200&auto=format&fit=crop',
        media_type: 'image',
        display_order: 1,
      },
    ],
  },
];
