import type { TrendItem } from '../types';

export const DEFAULT_FEATURED_TRENDS: TrendItem[] = [
  {
    id: 'trend-1',
    category: 'Tailoring',
    titleEn: 'Sculptural Tailoring',
    titleAr: 'الخياطة المنحوتة',
    subtitleEn: 'Sharp shoulders & dropped closures',
    subtitleAr: 'أكتاف هندسية وتفاصيل حرة',
    tagEn: '01 / STRUCTURE',
    tagAr: '01 / الهيكل',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'trend-2',
    category: 'Outerwear',
    titleEn: 'Raw Edge Cashmere',
    titleAr: 'الكشمير الطبيعي الخام',
    subtitleEn: '650gsm unlined double-face',
    subtitleAr: 'كشمير منغولي مزدوج الوجه',
    tagEn: '02 / TEXTURE',
    tagAr: '02 / الملمس',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'trend-3',
    category: 'Knitwear',
    titleEn: 'Heavy Rib Knitwear',
    titleAr: 'التريكو السميك المضلع',
    subtitleEn: 'Sculptural 7-gauge merino',
    subtitleAr: 'صوف ميرينو سميك عيار 7',
    tagEn: '03 / VOLUME',
    tagAr: '03 / الحجم',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'trend-4',
    category: 'Accessories',
    titleEn: 'Monolithic Leather',
    titleAr: 'الجلود المعمارية الصلبة',
    subtitleEn: 'Full-grain box calf & palladium',
    subtitleAr: 'جلد عجل فرنسي بقطع البلاديوم',
    tagEn: '04 / ACCENT',
    tagAr: '04 / التفاصيل',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'trend-5',
    category: 'Footwear',
    titleEn: 'Bevelled Square-Toe',
    titleAr: 'الأحذية بمقدمة مربعة',
    subtitleEn: 'Stacked leather & hand-waxed finish',
    subtitleAr: 'جلد ملمع بنعل كلاسيكي مكدس',
    tagEn: '05 / GROUND',
    tagAr: '05 / الأساس',
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&w=800&q=80',
  },
];

/**
 * Image Dimension Recommendations Guide for Perfect Visual Quality
 */
export const RECOMMENDED_IMAGE_SPECS = {
  heroBannerBg: {
    name_ar: 'خلفية البنر الترحيبي العريض (Top Hero Banner Background)',
    name_en: 'Top Welcome Hero Background',
    aspectRatio: '16:5 أو 16:6 (بانورامي عريض)',
    recommendedWidth: 1920,
    recommendedHeight: 600,
    minWidth: 1400,
    minHeight: 450,
    description_ar: 'صورة أفقية عريضة بدقة عالية لتغطية كامل العرض مع وضوح نصوص المقدمة',
    description_en: 'Ultra-wide horizontal backdrop for full-bleed hero presentation',
  },
  trendCard: {
    name_ar: 'كروت تريندات الموسم (Seasonal Trends Cards)',
    name_en: 'Seasonal Trends Cards',
    aspectRatio: '4:5 (عمودي بورتريه للأزياء)',
    recommendedWidth: 800,
    recommendedHeight: 1000,
    minWidth: 600,
    minHeight: 750,
    description_ar: 'صورة عمودية بنسبة 4:5 لإبراز تفاصيل القماش وتنسيق الإطلالة',
    description_en: 'Portrait fashion proportion 4:5 for editorial clarity',
  },
  productPrimary: {
    name_ar: 'الصورة الرئيسية للمنتج (Catalog Primary Product Image)',
    name_en: 'Catalog Primary Product Image',
    aspectRatio: '4:5 (بورتريه أزياء عالي الدقة)',
    recommendedWidth: 1200,
    recommendedHeight: 1500,
    minWidth: 800,
    minHeight: 1000,
    description_ar: 'أفضل مقاس لشبكة الكتالوج لتكبير وتفحص أدق تفاصيل الخامة والقصة',
    description_en: 'Ideal high-res 4:5 fashion cut for crisp masonry rendering',
  },
  productAngles: {
    name_ar: 'صور الزوايا والتفاصيل الإضافية (Product Detail Angles)',
    name_en: 'Product Detail Angles',
    aspectRatio: '4:5 أو 1:1',
    recommendedWidth: 1200,
    recommendedHeight: 1500,
    minWidth: 800,
    minHeight: 800,
    description_ar: 'صور مقربة للخامات والبطانة والدرزات الخلفية والجانبية',
    description_en: 'Close-ups of stitchwork, textures, and alternate styling',
  },
};
